kitchens/urls.py
from django.urls import path
from . import views

app_name="klaxonKitchen"
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.dashboard, name="home"),
    path('add_kitchen', views.add_kitchen, name="add_kitchen"),
    path('add_order', views.add_order, name="add_order"),
    path('kitchen/<int:kitchen_id>', views.kitchenDashboard, name="kitchen"),
    path('kitchen/delete/<int:kitchen_id>', views.kitchenDelete, name="kitchen_delete"),
    path('kitchen/delete/confirm/<int:kitchen_id>', views.kitchenDeleteConfirm, name="kitchen_delete_confirm"),
    path('update_order_status/<int:order_id>', views.update_order_status, name="update_order_status"),
    path('all_orders', views.all_orders, name="all_orders"),
    path('display_screen', views.display_screen, name="display_screen"),
    path('export_orders', views.export_orders, name="export_orders"), 
    path('export_kitchens', views.export_kitchens, name="export_kitchens"),
    path('delete_order/<int:order_id>', views.deleteOrder, name="delete_orders"),
    path('delete_order/confirm/<int:order_id>', views.deleteOrderConfirm, name="delete_orders_confirm"),
    path('reset_counter_all', views.reset_counter_all, name="reset_counters"),
    path('settings', views.settings, name="settings"),
    path('order_details/<int:order_id>', views.order_details, name="order_details"),
    path('order_update/<int:order_id>', views.order_update, name="order_update"),
]

klaxonKitchen/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('klaxonKitchen', include('kitchens.urls', namespace='klaxonKitchen')),
    path('', include('login.urls', namespace='login'))
]

login/urls.py
from django.urls import path, include
from . import views

app_name = "login"
urlpatterns = [
    path('', views.login_redirect, name="redirectToLogin"),
    path('login', views.login, name="login"),
    path('process_regi', views.process_regi),
    path('process_login', views.process_login),
    path('logout', views.logout, name="logout"),
    # path('process_user_info_change/', views.process_user_info_change),
    # path('process_user_pw_change/', views.process_user_pw_change),
    path('delete_user/<user_id>/', views.confirm_delete, name="delete"),
    path('delete_user/<user_id>/confirm/', views.delete_user, name="confirmDelete"),
]

kitchens/models.py
from django.db import models

# Create your models here.
class KitchenManager(models.Manager):
    def kitchen_validator(self, postData):
        errors = {}
        if Kitchen.objects.filter(name=postData['kitchen_name']):
            errors['nameExistenceError'] = "That Kitchen name already exists"
        if len(postData['kitchen_name']) < 3:
            errors['nameLenError'] = "The Name of the Kitchen needs to be at least 8 characters"
        if Kitchen.objects.filter(designation_id=postData['designationId']):
            errors['desigExistenceError'] = "That Designation already exists"

        return errors

class OrderManager(models.Manager):
    def Order_validator(self, postData):
        errors = {}
        if len(postData['orderNum']) < 1:
            errors['orderNumLenError'] = "You must enter an order number"
        if Kitchen.objects.filter(id=postData['kitchen_id']) and Order.objects.filter(order_num=postData['orderNum']):
            errors['orderNumExists'] = "The order number entered already exists"

        return errors


class Kitchen(models.Model):
    name = models.CharField(max_length=255)
    designation_id = models.CharField(max_length=255)
    daily_order_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = KitchenManager()
    def __str__ (self):
        return self.name


class Order(models.Model):
    ticket_num = models.CharField(max_length=255, default="0000")
    order_num = models.CharField(max_length=255)
    notes = models.TextField()
    status = models.CharField(max_length=255)
    kitchen = models.ForeignKey(Kitchen, related_name="orders", on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = OrderManager()

kitchens/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseRedirect
from django.contrib import messages
from .filters import OrderFilter
from kitchens.models import *
from login.models import *
import datetime
import csv

# Create your views here.
def dashboard(request):
    allKitchens = Kitchen.objects.all()
    allOrders = Order.objects.order_by("-id").all()

    myFilter = OrderFilter(request.GET, queryset=allOrders)
    allOrders = myFilter.qs

    context = {
        'allKitchens': allKitchens,
        'allOrders': allOrders,
        'myFilter': myFilter
    }
    return render(request, 'dashboard.html', context)

def add_kitchen(request):
    errors = Kitchen.objects.kitchen_validator(request.POST)

    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
    else:

        kitchen = Kitchen.objects.create(
            name=request.POST['kitchen_name'],
            designation_id=request.POST['designationId'].upper()
            )
    return redirect('klaxonKitchen:home')

def add_order(request):  
    errors = Order.objects.Order_validator(request.POST)  

    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
    else:
        kitchen = Kitchen.objects.get(id=request.POST['kitchen_id'])
        dateFormatted = datetime.datetime.today().strftime("%Y%m%d")
        count =  kitchen.daily_order_count + 1
        ticketNum = f"{kitchen.designation_id}-{dateFormatted}-{count}"
        orderNum = request.POST['orderNum']
        notes = request.POST['notes']
        status = "in progress"


        Order.objects.create(
            ticket_num=ticketNum,
            order_num=orderNum, 
            kitchen=kitchen,
            notes = notes,
            status = status
            )

        kitchen.daily_order_count += 1
        kitchen.save()

    return redirect('klaxonKitchen:home')

def kitchenDashboard(request, kitchen_id):
    kitchen = Kitchen.objects.order_by("-id").get(id=kitchen_id)
    allOrders = Order.objects.order_by("-id").all()

    context = {
        'kitchen': kitchen,
        'allOrders': allOrders
    }
    return render(request, 'kitchenDashboard.html', context)

def update_order_status(request, order_id):
    statuses = ["in progress", "ready", "done"]
    
    order = Order.objects.get(id=order_id)
    currentStatus = order.status.lower()

    if statuses.index(currentStatus) + 1 == len(statuses):
        nextStatus = 0
    else:
        nextStatus = statuses.index(currentStatus) + 1
    order.status = statuses[nextStatus]
    order.save()
    return redirect('klaxonKitchen:home')

def all_orders(request):
    all_orders = Order.objects.order_by('-id').all()

    myFilter = OrderFilter(request.GET, queryset=all_orders)
    all_orders = myFilter.qs

    context = {
        'allOrders': all_orders,
        'myFilter': myFilter
    }
    return render(request, 'allOrders.html', context)

def display_screen(request):
    context = {
        'allOrders': Order.objects.all()
    }
    return render(request, 'displayScreen.html', context)

def export_orders(request):
    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response)
    writer.writerow(['order_num', 'notes', 'status', 'kitchen', 'created_at', 'updated_at'])

    all_orders = Order.objects.order_by('-id').all()
    # myFilter = OrderFilter(request.GET, queryset=all_orders)
    # all_orders = myFilter.qs

    for order in all_orders.values_list('order_num', 'notes', 'status', 'kitchen', 'created_at', 'updated_at'):
        writer.writerow(order)

    response['Content-Disposition'] = 'attachment; filename="Orders.csv"'

    return response
    # return HttpResponse(all_orders)

def export_kitchens(request):
    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response)
    writer.writerow(['name', 'designation_id', 'daily_counter', 'created_at', 'updated_at'])

    for kitchen in Kitchen.objects.all().values_list('name', 'designation_id', 'daily_order_count', 'created_at', 'updated_at'):
        writer.writerow(kitchen)

    response['Content-Disposition'] = 'attachment; filename="Kitchens.csv"'

    return response

def deleteOrder(request, order_id):
    order = Order.objects.get(id=order_id)
    order.delete()

    return redirect('klaxonKitchen:all_orders')

def deleteOrderConfirm(request, order_id):
    context = {
        'order_id': order_id
    }
    return render(request, 'confirmOrderDelete.html', context)

def reset_counter_all(request):
    all_kitchens = Kitchen.objects.all()
    for kitchen in all_kitchens:
        kitchen.daily_order_count = 0
        kitchen.save()
    return redirect('klaxonKitchen:home')

def settings(request):
    return render(request, 'settings.html')

def kitchenDelete(request, kitchen_id):
    kitchen = Kitchen.objects.get(id=kitchen_id)
    kitchen.delete()
    return redirect('klaxonKitchen:home')

def kitchenDeleteConfirm(request, kitchen_id):
    context = {
        'kitchen_id': kitchen_id
    }
    return render(request, 'confirmKitchenDelete.html', context)

def order_details(request, order_id):
    current_order = Order.objects.get(id=order_id)
    allKitchens = Kitchen.objects.all()
    context = {
        'currentOrder': current_order,
        'allKitchens': allKitchens
    }
    return render(request, 'orderDetails.html', context)

def order_update(request, order_id):
    orderNum = request.POST['orderNum']
    kitchen = request.POST['kitchen']
    notes = request.POST['notes']

    linkedKitchen = Kitchen.objects.get(id=kitchen)

    orderToUpdate = Order.objects.get(id=order_id)

    orderToUpdate.order_num = orderNum
    orderToUpdate.kitchen = linkedKitchen
    orderToUpdate.notes = notes

    orderToUpdate.save()

    return redirect(f'/klaxonKitchenorder_details/{order_id}')

kitchens/templates/allOrders.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content">
        <div class="row dflex center justify-evenly">
            <h1>All Orders</h1>
            <div class="btns">

                <a class="button ml-3" href="{% url 'klaxonKitchen:export_orders' %}">Export Orders</a>
                <a class="button ml-3" href="{% url 'klaxonKitchen:export_kitchens' %}">Export Kitchens</a>
            </div>
        </div>
        <hr/>
        <div class="row">
            <form class="myFilter-row">
                {{ myFilter.form }}
                <button>Search</button>
            </form>
            <table class="u-full-width">
                <thead>
                    <tr>
                        <th>Order No</th>
                        <th>Kitchen</th>
                        <th>Created</th>
                        <th>Time Elapsed</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allOrders %}
                        <tr>
                            <td>{{ order.order_num }}</td>
                            <td>{{ order.kitchen.name }}</td>
                            <td>
                                <span class="time_created" data-timeInSeconds="{{ order.created_at.timestamp }}" ">{{ order.created_at }}</span>
                            </td>
                            <td>
                                <span class="time_elapsed"></span>
                            </td>
                            <td>
                                <a href="{% url 'klaxonKitchen:update_order_status' order.id %}" class="button statBtn">{{ order.status }}</a>
                            </td>
                            <td>
                                <a href="{% url 'klaxonKitchen:order_details' order.id %}">Edit</a>
                                |
                                <a href="{% url 'klaxonKitchen:delete_orders_confirm' order.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

kitchens/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" integrity="sha512-EZLkOqwILORob+p0BXZc+Vm3RgJBOe1Iq/0fiI7r/wJgzOFZMlsqTa29UEl6v6U6gsV4uIpsNZoV32YZqrCRCQ==" crossorigin="anonymous"/>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="../static/js/script.js"></script>
        <title>Klaxon Kitchen</title>
    </head>
    <body>
        {% include "navBar.html" %}
        {% block content %}{% endblock content %}
    </body>
</html>

kitchens/templates/confirmKitchenDelete.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content dflex-col center">
        <form action="" method="POST">
            <p>Are you sure you want to delete this kitchen?</p>
            <a class="button" href="{% url 'klaxonKitchen:kitchen_delete' kitchen_id %}">Yes</a>
            <a class="button" href="{% url 'klaxonKitchen:home' %}">No</a>
        </form>
    </div>
{% endblock %}

kitchens/templates/confirmOrderDelete.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content dflex-col center">
        <form action="" method="POST">
            <p>Are you sure you want to delete this Order?</p>
            <a class="button" href="{% url 'klaxonKitchen:delete_orders' order_id %}">Yes</a>
            <a class="button" href="{% url 'klaxonKitchen:home' %}">No</a>
        </form>
    </div>
{% endblock %}

kitchens/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content">
        <div class="row dflex justify-evenly">
            <div class="two columns dflex-col center left-col">
                <h3>All Kitchens</h3>
                <ul>
                    {% for kitchen in allKitchens %}
                        <li>
                            <a href="{% url 'klaxonKitchen:kitchen' kitchen.id %}" class="button">{{ kitchen.name }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
            <div class="six columns dflex-col center">
                <ul class="menuBar">
                    <li>
                        <a href="{% url 'klaxonKitchen:display_screen' %}" class="button yellow" target="_blank">Launch Display</a>
                    </li>
                    <li>
                        <a href="{% url 'klaxonKitchen:all_orders' %}" class="button">All Orders</a>
                    </li>
                    <li>
                        <a href="{% url 'klaxonKitchen:reset_counters' %}" class="button">Reset Counters</a>
                    </li>
                </ul>
                <h3>Active Orders</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Ticket No</th>
                            <th>Order No</th>
                            <th>Kitchen</th>
                            <th>Created</th>
                            <th>Time Elapsed</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in allOrders %}
                            {% if order.status != 'done' %}
                                <tr>
                                    <td>
                                        <a href="{% url 'klaxonKitchen:order_details' order.id %}">
                                            {{ order.ticket_num }}</a>
                                    </td>
                                    <td>{{ order.order_num }}</td>
                                    <td>{{ order.kitchen.name }}</td>
                                    <td>
                                        <span class="time_created" data-timeinseconds="{{ order.created_at.timestamp }}" ">{{ order.created_at }}</span>
                                    </td>
                                    <td>
                                        <span class="time_elapsed"></span>
                                    </td>
                                    <td>
                                        <a href="{% url 'klaxonKitchen:update_order_status' order.id %}" class="button statBtn">{{ order.status }}</a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="three columns dflex-col center right-col">
                <form action="{% url 'klaxonKitchen:add_order' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="orderNum" id="orderNum" placeholder="Order Number">
                        <select name="kitchen_id" id="kitchenOption" value="aaa">
                            <option disabled="disabled" selected="selected" hidden="hidden" value="None">Pick a Kitchen</option>
                            {% for kitchen in allKitchens %}
                                <option value="{{ kitchen.id }}">{{ kitchen.name }}</option>
                            {% endfor %}
                        </select>
                        <textarea name="notes" class="u-full-width" id="orderNotes" cols="30" rows="10" placeholder="Notes"></textarea>
                        <button class="button-chief u-full-width orderFormBtn disabled" disabled>Create</button>
                    </form>
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>
                                    <span class="errorMessage">{{ message }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <hr/>
                    <form class="myFilter-col">
                        {{ myFilter.form }}
                        <button>Search</button>
                    </form>
                </div>
            </div>
        </div>
    {% endblock content %}

kitchens/templates/displayScreen.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" integrity="sha512-EZLkOqwILORob+p0BXZc+Vm3RgJBOe1Iq/0fiI7r/wJgzOFZMlsqTa29UEl6v6U6gsV4uIpsNZoV32YZqrCRCQ==" crossorigin="anonymous"/>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="../static/js/script.js"></script>
        <script src="../static/js/displayScript.js"></script>
        <title>Klaxon Display</title>
    </head>
    <body class="yellow">
        <div class="body-content">
            <div class="row dflex center">
                <h1>Orders</h1>
            </div>
            <div class="row">
                <div class="six columns dflex-col white displayBox">
                    <h3>In Progress</h3>
                    <table class="u-full-width displayTables">
                        <thead>
                            <tr>
                                <th>Order No</th>
                                <th>Kitchen</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in allOrders %}
                                {% if order.status == 'in progress' %}
                                    <tr>
                                        <td>{{ order.order_num }}</td>
                                        <td>{{ order.kitchen.name }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="six columns dflex-col white displayBox">
                    <h3>Ready For Pickup</h3>
                    <table class="u-full-width displayTables">
                        <thead>
                            <tr>
                                <th>Order No</th>
                                <th>Kitchen</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in allOrders %}
                                {% if order.status == 'ready' %}
                                    <tr>
                                        <td>{{ order.order_num }}</td>
                                        <td>{{ order.kitchen.name }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </body>
</html>

kitchens/templates/kitchenDashboard.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content">
        <div class="row header dflex justify-between center">
            <h1 class="dflex center">{{ kitchen.name }}</h1>
            <a href="{% url 'klaxonKitchen:kitchen_delete_confirm' kitchen.id %}" class="button button-chief text-white red">Delete Kitchen</a>
        </div>
        <div class="row">
            <table class="u-full-width displayTables">
                <thead>
                    <tr>
                        <th>Order No</th>
                        <th>Notes</th>
                        <th>Created</th>
                        <th>Updated at</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allOrders %}
                        {% if order.kitchen.id == kitchen.id %}
                            <tr>
                                <td>{{ order.order_num }}</td>
                                <td>{{ order.notes }}</td>
                                <td>
                                    <span class="time_created" data-timeInSeconds="{{ order.created_at.timestamp }}" ">{{ order.created_at }}</span>
                                </td>
                                <td>
                                    {{ order.updated_at }}
                                </td>
                                <td>{{ order.status }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

kitchens/templates/navBar.html
{% block nav %}
    <div class="navbar">
        <a href="{% url 'klaxonKitchen:home' %}">
            <img src="../static/img/Klaxon-Logo-Web-White.png" alt="Klaxon logo"/></a>
        <h1>Klaxon Kitchen</h1>
        <div class="btns">
            <a class="button button-chief" href="{% url 'klaxonKitchen:settings' %}">Settings</a>
            <a class="button button-chief" href="{% url 'login:logout' %}">Logout</a>
        </div>
    </div>
{% endblock %}

kitchens/templates/orderDetails.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content dflex-col center">

        <h1>Order Details for
            {{ currentOrder.order_num }}</h1>
        <a class="button button-chief" href="{% url 'klaxonKitchen:delete_orders_confirm' currentOrder.id %}">Delete</a>
        <form action="{% url 'klaxonKitchen:order_update' currentOrder.id %}" method="POST">
            {% csrf_token %}
            <p>
                <strong>Ticket Number:
                </strong>
                {{ currentOrder.ticket_num }}
            </p>
            <label for="orderNum">Order Number:</label>
            <input type="text" name="orderNum" id="orderNum" value="{{ currentOrder.order_num }}"/>
            <label for="kitchen">Kitchen:</label>
            <select name="kitchen" id="kitchen">
                <option value="{{ currentOrder.kitchen.id }}">{{ currentOrder.kitchen }}</option>
                {% for kitchen in allKitchens %}
                    {% if kitchen != currentOrder.kitchen %}
                        <option value="{{ kitchen.id }}">{{ kitchen }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <label for="notes">Notes:</label>
            <textarea name="notes" id="notes" cols="30" rows="10">{{ currentOrder.notes }}</textarea>
            <br>
                <button>Change</button>
            </form>
        </div>
    {% endblock %}

kitchens/templates/settings.html
{% extends "base.html" %}
{% block content %}
    <div class="body-content settings">
        <h1>Settings</h1>
        <div class="card">

            <form action="{% url 'klaxonKitchen:add_kitchen' %}" method="POST">
                {% csrf_token %}
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <input type="text" class="u-full-width" name="kitchen_name" id="kitchen_name" placeholder="Kitchen Name"/>
                <input type="text" name="designationId" id="designationId" placeholder="Designation Id"/>
                <button class="button-chief">Create</button>
            </form>
        </div>
        <div class="card">
            <div class="dflex justify-evenly center text-red">
                <a class="button button-chief" href="{% url 'login:delete' activeUser.id %}">Delete User</a>
                <h5>Warning this cannot be undone</h5>
            </div>
        </div>
    </div>
{% endblock %}